### ISSUE TITLE
 Search failed. (Search API failed.) 

### ISSUE THREAD

**Issue by GitCartel** [gimite/tweet-search-stream#2]
http://tweet-search-stream.gimite.net/?hl=en

**Comment by GitCartel** [comment]
image

**Comment by GitCartel** [comment]
https://i.imgur.com/2nMwCPK.jpg

**Comment by GitCartel** [comment]
Site is now offline.
I hope it can be restored its a very useful tool.

thx

**Comment by GitCartel** [comment]
Site back up but: Search failed. (Search API failed.)

**Comment by gimite** [comment]
Thanks for the report. Unfortunately I'm on a trip and hard to debug the issue in a week or so. I will take a look in a week.

**Comment by GitCartel** [comment]
OK thank you

**Comment by gimite** [comment]
Sorry for taking long but I believe it has been fixed. Let me know if you still encounter any issues.

**Comment by GitCartel** [comment]
thank you!

**Comment by GitCartel** [comment]
It does work when you hit seach but it wont search live.
It shows 4-5 results then sits there, no  new results.

**Comment by gimite** [comment]
Thanks for the report. It looked hitting rate limit. I changed the reconnection parameters so that it hopefully no longer hit the rate limit. I will see how it goes.

Note that you sometimes need to wait for up to 1 minute until it starts getting live results. This is the same as before.

**Comment by ghost** [comment]
thank you and God Bless
